CLEANDEP=$(foreach dir,$(SUBDIRS),$(MAKE) -C $(dir) clean;)

clean::
	@-rm -f *~
	@$(CLEANDEP)

distclean::CLEANDEP=
distclean::clean
	@$(foreach dir,$(SUBDIRS),$(MAKE) -C $(dir) distclean;)
	@-rm -f Makefile
